import React from 'react'
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';


const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'お問い合わせ',
  description: 'Generated by create next app',
};

function Contact() {
  return (
    <div>
      
    </div>
  )
}

export default Contact
