import React from 'react'
import styles from '../../../styles/Registry.module.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';


const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: '会員登録',
  description: 'Generated by create next app',
};


const submit =()=>{

}

function Registry() {
  return (
    <div>

      <div className={styles.main}>
        <h1>会員登録</h1>
        <div className={styles.tableCovered}>
          <h2 className={styles.h2A}>ユーザー情報
            </h2>
          <table className={styles.table}>
            <tbody className={styles.userInfo}>
              {/* tr: table row */}
              {/* th: table header */}
              {/* td: tabel data */}
              <tr className={styles.tr}>
                <th className={styles.th}>
                  ユーザーネーム<span className={styles.span}>※</span>
                </th>
                <td className={styles.td}>
                  <input type="text" id="name" placeholder="健康管理" className={styles.inputT}/>                </td>
              </tr>
              <tr className={styles.tr}>
                <th className={styles.th}>
                  Email<span className={styles.span}>※</span>
                </th>
                <td className={styles.td}>
                  <input type="email" name="email" id="email" placeholder='XXX@nurtrition.com' maxLength={256} className={styles.inputT}/>
                </td>
              </tr>
              <tr className={styles.tr}>
                <th className={styles.th}>
                パスワード<span className={styles.span}>※</span>
                </th>
                <td className={styles.td}>
                  <input type="password" name="password" id="password" placeholder='********' maxLength={16} minLength={8} className={styles.inputT}/>
                  <p>半角英字、数字を含めて8文字以上16字以内で設定してください</p>
                </td>
              </tr>
              <tr className={styles.tr}>
                <th className={styles.th}>
                確認パスワード<span className={styles.span}>※</span>
                </th>
                <td className={styles.td}>
                  <input type="password" name="passwordConfirmation" id="passwordConfirmation" placeholder='********' maxLength={16} minLength={8} className={styles.inputT}/>
                  <p>入力したパスワードと同じものを入力してください
                  </p>
                </td>
              </tr>
            </tbody>
            </table>

            <h2 className={styles.h2B}>身体情報
            </h2>
            <table className={styles.table}>
            <tbody className={styles.PhysicalInfo}>
            <tr className={styles.tr}>
                <th className={styles.th}>
                  身長
                </th>
                <td className={styles.td}>
                  <input type="text" name="height" id="height" placeholder='158' maxLength={3} minLength={2} className={styles.inputN}/>cm
                </td>
              </tr>
              <tr className={styles.tr}>
                <th className={styles.th}>
                  体重
                </th>
                <td className={styles.td}>
                  <input type="text" name="weight" id="weight" placeholder='48' maxLength={3} minLength={2} className={styles.inputN}/>kg
                </td>
              </tr>
              <tr className={styles.tr}>
                <th className={styles.th}>
                  生年月日
                </th>
                <td className={styles.td}>
                  <input type="text" name="age" id="age" placeholder='19990625' maxLength={8} minLength={8} className={styles.inputT}/>
                </td>
              </tr>
              <tr className={styles.tr}>
                <th className={styles.th}>
                  性別
                </th>
                <td className={styles.td}>
                  <div className={styles.vertical}>
                    {/* name="gender"を設定することでどちらかしか選択できないようにする */}
                    <label htmlFor="male">
                      <input type="radio" name="gender" id="male" checked/>男性
                    </label>
                    <label htmlFor="female">
                      <input type="radio" name="gender" id="female" />女性
                    </label>
                  </div>
                </td>
              </tr>
            </tbody>
            </table>
            <button className={styles.btn} >登録する</button>
        </div>
      </div>
    </div>
  )
}

export default Registry
