import React from 'react'
import styles from '../../../styles/Registry.module.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';


const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: '会員登録',
  description: 'Generated by create next app',
};


function Registry() {
  return (
    <div>

      <div className={styles.main}>
        <h1>会員登録</h1>
        <div className={styles.tableCovered}>
          <h2 className={styles.h2A}>ユーザー情報
            </h2>
          <table className={styles.table}>
            <tbody className={styles.userInfo}>
              {/* tr: table row */}
              {/* th: table header */}
              {/* td: tabel data */}
              <tr className={styles.tr}>
                <th className={styles.th}>
                  ユーザーネーム<span className={styles.span}>※</span>
                </th>
                <td className={styles.td}>
                  <input type="text" className={styles.inputT}/>
                </td>
              </tr>
              <tr className={styles.tr}>
                <th className={styles.th}>
                  Email<span className={styles.span}>※</span>
                </th>
                <td className={styles.td}>
                  <input type="email" name="email" id="email" placeholder='XXX@nurtrition.com' className={styles.inputT}/>
                </td>
              </tr>
              <tr className={styles.tr}>
                <th className={styles.th}>
                パスワード<span className={styles.span}>※</span>
                </th>
                <td className={styles.td}>
                  <input type="password" name="password" id="password" placeholder='********' className={styles.inputT}/>
                </td>
              </tr>
              <tr className={styles.tr}>
                <th className={styles.th}>
                確認パスワード<span className={styles.span}>※</span>
                </th>
                <td className={styles.td}>
                  <input type="password" name="passwordConfirmation" id="passwordConfirmation" placeholder='********' className={styles.inputT}/>
                </td>
              </tr>
            </tbody>
            </table>

            <h2 className={styles.h2B}>身体情報
            </h2>
            <table className={styles.table}>
            <tbody className={styles.PhysicalInfo}>
            <tr className={styles.tr}>
                <th className={styles.th}>
                  身長
                </th>
                <td className={styles.td}>
                  <input type="number" name="height" id="height" placeholder='158' className={styles.inputN}/>cm
                </td>
              </tr>
              <tr className={styles.tr}>
                <th className={styles.th}>
                  体重
                </th>
                <td className={styles.td}>
                  <input type="number" name="weight" id="weight" placeholder='48' className={styles.inputN}/>kg
                </td>
              </tr>
              <tr className={styles.tr}>
                <th className={styles.th}>
                  生年月日
                </th>
                <td className={styles.td}>
                  <input type="date" name="age" id="age" className={styles.inputT}/>
                </td>
              </tr>
              <tr className={styles.tr}>
                <th className={styles.th}>
                  性別
                </th>
                <td className={styles.td}>
                  <div className={styles.vertical}>
                  <div className="male">
                  <input type="radio" name="male" id="male" />男性
                  </div>
                  <div className="female">
                  <input type="radio" name="female" id="female" />女性
                  </div>
                  </div>
                </td>
              </tr>
            </tbody>
            </table>
        </div>
      </div>
    </div>
  )
}

export default Registry
