import React from 'react'
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import styles from "../../../styles/Login.module.css"


// const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'ログイン',
//   description: 'Generated by create next app',
// };

function Login() {
  return (
    <div className={styles.main}>
      <form className={styles.flex}>
        <div className={styles.flex2}>
          <span className={styles.span}>USERNAME</span>
          <input type="email" className={styles.input} placeholder="ログインID（登録メールアドレス）" maxLength={250}/>
        </div>
        <div className={styles.flex2}>
          <span className={styles.span}>PASSWORD</span>
          <input type="password" className={styles.input} maxLength={16} placeholder="パスワード"/>
        </div>
        <button className={styles.btn}>SIGN IN</button>
      </form>
  </div>  
  )
}

export default Login
